apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dicelogger.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dicelogger.labels" . | nindent 4 }}
data:
  config.txt: |-
    {{- .Values.loglines | nindent 4}}