fluent-bit:
  enabled: true
  config:
    batchWait: "1s"
    batchSize: "1048576"
    removeKeys:
    - kubernetes
    - stream
    - custom
    customFieldExists:
    - my_custom_label
    - error
    - critical
    - fatal
    labelMap:
      kubernetes:
        namespace_name: namespace
        labels:
          app.kubernetes.io/name: app
          helm.sh/chart: chart
        host: node
        container_name: container
        pod_name: instance
      stream: stream
      custom:
        my_custom_label: custom_error_level
  image:
    repository: demonsthere/fluent-bit-loki
    tag: custom-field
    pullPolicy: Always

promtail:
  enabled: false
grafana:
  enabled: true
